### ISSUE TITLE
Implement ddclient-based hostname callback

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-admin#177]
and document, so that dyn ip providers can be automatically updated.

**Comment by Tiger862000** [comment]
Hi Ernst,
please implement ddclient or similar in UBOS. I'm even struggeling to get ddclient installed on arch arm, because of missing yaourt support. Even built ddclient myself, but didn't got it running with systemd :-(

**Comment by jernst** [comment]
Please paste here how you built it, and how you tried to run it with systemd.

**Comment by Tiger862000** [comment]
hi, sry for my late reply I had to take some vacations. I used several solutions, but none of them worked. This is what I did:

1.) Install DDClient
 a) Build yourself
Download link: http://freefr.dl.sourceforge.net/project/ddclient/ddclient/ddclient-3.8.3/ddclient-3.8.3.tar.gz
`curl -O -# http://freefr.dl.sourceforge.net/project/ddclient/ddclient/ddclient-3.8.3/ddclient-3.8.3.tar.gz`
```
tar -xzf ddclient-3.8.3.tar.gz
cd ddclient-3.8.3
```
(`nano README.md`)
```
su root
cp ddclient /usr/sbin/
mkdir /etc/ddclient
mkdir /var/cache/ddclient
cp sample-etc_ddclient.conf /etc/ddclient/ddclient.conf
```

Install dependencies
`pacman -Sy perl-digest-sha1
pacman -Sy net-tools`

b) Install using yaourt
Install dependencies
Base-devel
`pacman -S base-devel`
Package-query
```
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
```
`makepkg -si`

> → Dependency Error: yajl>=2.0

Instructions:
http://www.presence4you.de/viewtopic.php?t=225

2.) Configure DDClient:
ddclient configuration file (using kate instead of nano in Kubuntu, or gedit instead of nano in Ubuntu): 
(su root)
`nano /etc/ddclient/ddclient.conf`

The following is the format of the DDClient configuration:

> use=web, web=dynamicdns.park-your-domain.com/getip
> protocol=namecheap 
> server=dynamicdns.park-your-domain.com 
> login=yourdomain.com
> password=your dynamic dns password
> yourhost


Get the Dynamic DNS Password from DDNS provider, like for namecheap here:



3.) Create Systemd Unit for ddclient and start it:
[](https://wiki.archlinux.org/index.php/Dynamic_DNS#Starting_ddclient_after_networking_is_up)

`systemctl edit --full ddclient.service`

> [Unit]
> Description=Dynamic DNS Update Client
> After=network.target
> PartOf=network-online.target
> 
> [Service]
> Type=forking
> PIDFile=/var/run/ddclient.pid
> ExecStart=/usr/bin/ddclient
> 
> [Install]
> WantedBy=network-online.target


```
systemctl enable ddclient.service
systemctl start ddclient.service

reboot
```

**Comment by jernst** [comment]
Added to repo (currently dev channel only, will get to yellow in next release). Seems to work fine.
