### ISSUE TITLE
backup to alternative locations

### ISSUE THREAD

**Issue by Tiger862000** [uboslinux/ubos-admin#215]
It would be great to be able to backup to alternative locations than Amazon cloud for the more paranoid people like me :-).
Easiest for noobs would be to backup to a second UBOS device that is solely used for backups. Advanced functionality could be to backup to personal NAS.

**Comment by jernst** [comment]
You can encrypt your backup before uploading it to Amazon, so you should be fine even if you are paranoid :-) The trouble with UBOS-to-other-device backup is the setup and the security of the setup because nfs and so forth aren't great at that.

On the other hand, if you don't mind two commands instead of one, what about you create a local backup file, and sftp it to another device?

**Comment by Tiger862000** [comment]
both options sound great. I guess restoring with the 2nd method wouldn't be that easy?

What if my SD card crashes? How do I restore then?

**Comment by jernst** [comment]
Re-install UBOS on new card. Then: `ubos-admin restore --url <url-of-backup>` or manually copy file to device and `ubos-admin restore --file <backupfile>`.

**Comment by jernst** [comment]
I'm going to close this in favor of https://github.com/uboslinux/ubos-docs/issues/39
