### ISSUE TITLE
Add Message for --letsencrypt when installing using IP only - Domain required

### ISSUE THREAD

**Issue by jpmull** [uboslinux/ubos-admin#252]
I have managed to get Nextcloud 11 up on an EC2 instance, but every time I try, --TLS --Letsencrypt fails.  I really would like to use https.  Is there anyway to fix it after the site is up?  I have no idea why it fails.  I'm just following along the steps to install.  Http://34.205.155.87 is the current site - waiting on dns to propagate.

**Comment by jernst** [comment]
For this to work, your Nextcloud instance must:

- have a public IP address (check)
- you must have an official host name (say `nextcloud.practicetheguitar.com`) that points its A record to your IP address (not that I can see)
- you must have specified that host name when setting up the site with `ubos-admin createsite --tls --letsencrypt`.

In that sequence.

Having said that, the bug is that we should not allow `createsite --tls --letsencrypt` with a hostname that is an IP address or mDNS address.

**Comment by jpmull** [comment]
I do have the hostname and A record set up - cloud.practicetheguitar.com

So I guess the the proper steps should be:

1. Setup Ec2
2. Setup domain and A record pointing to EC2
3. Wait for DNS to propagate
4. ssh -i <your-key-file> -l shepherd <cloud.practicetheguitar.com>
5. ubos-admin createsite --tls --letsencrypt

**Comment by jernst** [comment]
Actually, there's still a bug here, which is that we don't provide an error message when clearly there should be one.

**Comment by jpmull** [comment]
Sorry, I'm a noob.  I'm trying to follow the steps I laid out below.  I am being asked for shepherd@cloud.practicetheguitar.com's password, but I never set one up.  What am I doing wrong?

**Comment by jernst** [comment]
You don't set it up yourself; between AWS, cloud-init (something we run on UBOS) and UBOS, it sets up the shepherd account based on the key pair you chose to use with this EC2 instance in the AWS GUI. See http://ubos.net/docs/users/shepherd-staff.html#ubos-staff-device-configuration-cloud

Chances are that you aren't specifying the correct private key to use when attempting to log on. (`ssh -i`)

**Comment by jpmull** [comment]
okay.  Thanks again, I really appreciate your patience.  I gotta get some sleep!
